package com.cmips.baw.dto;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * DTO representing a payment record to be sent to SCO (State Controller's Office).
 *
 * This is the outbound file format - approved timesheets converted to payment requests.
 * SCO uses this to issue warrants to IHSS providers.
 *
 * Legacy Reference: PRDR120A - Payment request file to SCO
 */
public record PaymentRecord(
    /**
     * Unique payment request ID generated by our system.
     */
    String paymentRequestId,

    /**
     * Provider ID receiving the payment.
     */
    String providerId,

    /**
     * Provider name for verification.
     */
    String providerName,

    /**
     * Associated case number.
     */
    String caseNumber,

    /**
     * County code (2-digit California county code).
     */
    String countyCode,

    /**
     * Pay period start date.
     */
    LocalDate payPeriodStart,

    /**
     * Pay period end date.
     */
    LocalDate payPeriodEnd,

    /**
     * Regular hours worked.
     */
    BigDecimal regularHours,

    /**
     * Overtime hours worked.
     */
    BigDecimal overtimeHours,

    /**
     * Total hours (regular + overtime + sick + vacation + holiday).
     */
    BigDecimal totalHours,

    /**
     * Calculated payment amount.
     * In real system, this would be: (regularHours * rate) + (overtimeHours * rate * 1.5)
     */
    BigDecimal paymentAmount,

    /**
     * Source timesheet ID for audit trail.
     */
    Long timesheetId,

    /**
     * Payment type: REGULAR, ADJUSTMENT, RETROACTIVE
     */
    PaymentType paymentType
) {
    public enum PaymentType {
        REGULAR,      // Normal bi-weekly payment
        ADJUSTMENT,   // Correction to previous payment
        RETROACTIVE   // Back-dated payment
    }

    /**
     * Builder for creating PaymentRecord from timesheet data.
     */
    public static PaymentRecord fromTimesheet(
            Long timesheetId,
            String providerId,
            String providerName,
            String caseNumber,
            String countyCode,
            LocalDate payPeriodStart,
            LocalDate payPeriodEnd,
            BigDecimal regularHours,
            BigDecimal overtimeHours,
            BigDecimal totalHours,
            BigDecimal hourlyRate) {

        // Calculate payment: regular hours at normal rate + overtime at 1.5x
        BigDecimal regularPay = regularHours.multiply(hourlyRate);
        BigDecimal overtimePay = overtimeHours.multiply(hourlyRate).multiply(BigDecimal.valueOf(1.5));
        BigDecimal totalPayment = regularPay.add(overtimePay);

        // Generate unique payment request ID
        String paymentRequestId = String.format("PAY-%s-%s-%d",
            countyCode,
            payPeriodEnd.toString().replace("-", ""),
            timesheetId);

        return new PaymentRecord(
            paymentRequestId,
            providerId,
            providerName,
            caseNumber,
            countyCode,
            payPeriodStart,
            payPeriodEnd,
            regularHours,
            overtimeHours,
            totalHours,
            totalPayment,
            timesheetId,
            PaymentType.REGULAR
        );
    }
}
